// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://numsihpyierdzznzkcsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51bXNpaHB5aWVyZHp6bnprY3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4OTI5NTcsImV4cCI6MjA3ODQ2ODk1N30.4vMDqOyIT9YgoL5oRqoAtte0rjjA12Ajjjt5DBJYt3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});