// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtfbocwsfxwrzfzvzgja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZmJvY3dzZnh3cnpmenZ6Z2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxODgxNDQsImV4cCI6MjA4MDc2NDE0NH0.lwJIr6yG5Yl-ulLJCuDoIwliMhXRMGK5HXHKtUdq-bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});